name: "publish"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install frontend dependencies
        working-directory: ./lonewolf-tauri
        run: make -f Makefile.win npm-install

      - name: compile assets
        working-directory: ./lonewolf-tauri
        run: make -f Makefile.win icons

      - name: check and test
        working-directory: ./lonewolf-tauri
        run: make -f Makefile.win check test-unit

      - id: get-version
        run: |
          version=$(echo ${{github.ref}} | grep -oP "[\d]+\.[\d]+\.[\d]+")
          echo "::set-output name=version::$version"

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./lonewolf-tauri/src-tauri
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Lonewolf v__VERSION__"
          releaseBody: "This build was automatically created. Check the assets below for the binaries for your platform :D"
          appVersion: ${{steps.get-version.outputs.version}}
          prerelease: ${{contains(github.ref, 'rc')}}
