name: "publish"

on:
  push:
    branches:
      - main

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: change Makefile (windows only)
        if: matrix.platform == 'windows-latest'
        run: |
          cd lonewolf-tauri
          mv Makefile Makefile.lin
          mv Makefile.win Makefile
          cd ..

      - name: install frontend dependencies
        run: |
          cd lonewolf-tauri
          make npm-install
          cd ..

      - name: compile assets
        run: |
          cd lonewolf-tauri
          make icons
          make tauri-icons
          cd ..
      
      - name: check and test
        run: |
          cd lonewolf-tauri
          make check
          make test-unit
          cd ..

      # - name: build executable
      #   run: |
      #     cd lonewolf-tauri
      #     make build
      #     cd ..

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./lonewolf-tauri
          tagName: lonewolf-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "Lonewolf v__VERSION__"
          releaseBody: "This build was automatically created. Check the assets below for the binaries for your platform :D"
